services:
  # configuration manager for NiFi
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: on-failure
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  # version control for nifi flows
  registry:
    image: 'apache/nifi-registry:2.1.0'
    restart: on-failure
    ports:
      - "18080:18080"
    environment:
      - LOG_LEVEL=INFO
      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
      - NIFI_REGISTRY_FLOW_PROVIDER=file
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    volumes:
      - ./nifi_registry_database:/opt/nifi-registry/nifi-registry-current/database
      - ./nifi_registry_flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      #- ./nifi_registry_conf:/opt/nifi-registry/nifi-registry-current/conf
# data extraction, transformation and load service

  elasticsearch:
    image: elasticsearch:8.17.0
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=openstack
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw

  nifi:
    build: ./nifi_service
    restart: on-failure
    ports:
      - '8091:8443'
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTPS_HOST=${NIFI_WEB_HTTPS_HOST:-nifi}
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=30 sec
      - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_PROPS_KEY:-12345678901234567890A}
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME:-admin}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD:-ZLvgNGRBDl7MEMR7}
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl -k https://127.0.0.1:8091/nifi/ || exit 1}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 5
    volumes:
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      # uncomment the next line after copying the /conf directory from the container to your local directory to persist NiFi flows
      #- ./nifi_conf:/opt/nifi/nifi-current/conf

volumes:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_content_repository:
  nifi_provenance_repository:
  nifi_state:
  nifi_logs:
  elasticsearch_data:
