services:
  # configuration manager for NiFi
  zookeeper:
    image: 'bitnami/zookeeper:latest'  # latest image as of 2021-11-09.
    restart: on-failure
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  # version control for nifi flows
  registry:
    image: 'apache/nifi-registry:1.28.0'  # latest image as of 2021-11-09.
    restart: on-failure
    ports:
      - "18080:18080"
    environment:
      - LOG_LEVEL=INFO
      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
      - NIFI_REGISTRY_FLOW_PROVIDER=file
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    volumes:
      - ./nifi_registry_database:/opt/nifi-registry/nifi-registry-current/database
      - ./nifi_registry_flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      #- ./nifi_registry_conf:/opt/nifi-registry/nifi-registry-current/conf
# data extraction, transformation and load service
  nifi:
    image: 'apache/nifi:1.28.0'  # latest image as of 2021-11-09.
    restart: on-failure
    ports:
      - '8091:8080'
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=30 sec
      - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8091/nifi/}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 5
    volumes:
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      # uncomment the next line after copying the /conf directory from the container to your local directory to persist NiFi flows
      #- ./nifi_conf:/opt/nifi/nifi-current/conf

volumes:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_content_repository:
  nifi_provenance_repository:
  nifi_state:
  nifi_logs:
